<?php

/**
 * This is the model base class for the table "mspasien2".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mspasien2".
 *
 * Columns in table "mspasien2" available as properties of the model,
 * followed by relations of table "mspasien2" available as properties of the model.
 *
 * @property integer $id
 * @property integer $nomr
 * @property string $nama
 * @property string $sex
 * @property string $tempat_lahir
 * @property string $tgl_lahir
 * @property string $alamat
 * @property integer $agama
 * @property string $hp
 * @property string $pekerjaan
 * @property string $pendidikan
 * @property string $status
 * @property string $penanggung_jawab
 * @property string $hub_dgn_pasien
 *
 * @property Refagama $agama0
 */
abstract class BaseMspasien2 extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mspasien2';
	}

	public static function representingColumn() {
		return 'nama';
	}

	public function rules() {
		return array(
			array('nomr, nama, sex, tgl_lahir, penanggung_jawab', 'required'),
			array('nomr, agama', 'numerical', 'integerOnly'=>true),
			array('nama, tempat_lahir, pekerjaan, penanggung_jawab', 'length', 'max'=>100),
			array('sex, status', 'length', 'max'=>1),
			array('alamat', 'length', 'max'=>200),
			array('hp', 'length', 'max'=>15),
			array('pendidikan, hub_dgn_pasien', 'length', 'max'=>50),
			array('tempat_lahir, alamat, agama, hp, pekerjaan, pendidikan, status, hub_dgn_pasien', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nomr, nama, sex, tempat_lahir, tgl_lahir, alamat, agama, hp, pekerjaan, pendidikan, status, penanggung_jawab, hub_dgn_pasien', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'agama0' => array(self::BELONGS_TO, 'Refagama', 'agama'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nomr' => Yii::t('app', 'Nomr'),
			'nama' => Yii::t('app', 'Nama'),
			'sex' => Yii::t('app', 'Sex'),
			'tempat_lahir' => Yii::t('app', 'Tempat Lahir'),
			'tgl_lahir' => Yii::t('app', 'Tgl Lahir'),
			'alamat' => Yii::t('app', 'Alamat'),
			'agama' => Yii::t('app', 'Agama'),
			'hp' => Yii::t('app', 'Hp'),
			'pekerjaan' => Yii::t('app', 'Pekerjaan'),
			'pendidikan' => Yii::t('app', 'Pendidikan'),
			'status' => Yii::t('app', 'Status'),
			'penanggung_jawab' => Yii::t('app', 'Penanggung Jawab'),
			'hub_dgn_pasien' => Yii::t('app', 'Hub Dgn Pasien'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nomr', $this->nomr);
		$criteria->compare('nama', $this->nama, true);
		$criteria->compare('sex', $this->sex, true);
		$criteria->compare('tempat_lahir', $this->tempat_lahir, true);
		$criteria->compare('tgl_lahir', $this->tgl_lahir, true);
		$criteria->compare('alamat', $this->alamat, true);
		$criteria->compare('agama', $this->agama);
		$criteria->compare('hp', $this->hp, true);
		$criteria->compare('pekerjaan', $this->pekerjaan, true);
		$criteria->compare('pendidikan', $this->pendidikan, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('penanggung_jawab', $this->penanggung_jawab, true);
		$criteria->compare('hub_dgn_pasien', $this->hub_dgn_pasien, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}