<?php

/**
 * This is the model base class for the table "mspasien3".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mspasien3".
 *
 * Columns in table "mspasien3" available as properties of the model,
 * followed by relations of table "mspasien3" available as properties of the model.
 *
 * @property integer $id
 * @property string $nama
 * @property integer $agama
 *
 * @property Refagama $agama0
 */
abstract class BaseMspasien3 extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mspasien3';
	}

	public static function representingColumn() {
		return 'nama';
	}

	public function rules() {
		return array(
			array('nama, agama', 'required'),
			array('agama', 'numerical', 'integerOnly'=>true),
			array('nama', 'length', 'max'=>45),
			array('id, nama, agama', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'agama0' => array(self::BELONGS_TO, 'Refagama', 'agama'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nama' => Yii::t('app', 'Nama'),
			'agama' => Yii::t('app', 'Agama'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nama', $this->nama, true);
		$criteria->compare('agama', $this->agama);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}