<?php

/**
 * This is the model base class for the table "ref_kode_tambah".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RefKodeTambah".
 *
 * Columns in table "ref_kode_tambah" available as properties of the model,
 * followed by relations of table "ref_kode_tambah" available as properties of the model.
 *
 * @property integer $id
 * @property string $kodetambah
 *
 * @property Dattarif[] $dattarifs
 */
abstract class BaseRefKodeTambah extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ref_kode_tambah';
	}

	public static function representingColumn() {
		return 'kodetambah';
	}

	public function rules() {
		return array(
			array('kodetambah', 'required'),
			array('kodetambah', 'length', 'max'=>45),
			array('id, kodetambah', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'dattarifs' => array(self::HAS_MANY, 'Dattarif', 'kdtambah'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'kodetambah' => Yii::t('app', 'Kodetambah'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('kodetambah', $this->kodetambah, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}