<?php

/**
 * This is the model base class for the table "tindakan_igd".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TindakanIgd".
 *
 * Columns in table "tindakan_igd" available as properties of the model,
 * followed by relations of table "tindakan_igd" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idreg
 * @property integer $idrwt
 * @property integer $kdtindakan
 * @property string $qty
 * @property string $harga_satuan
 * @property integer $jns_bayar
 *
 * @property RegisterIgd $idreg0
 * @property Dattarif $kdtindakan0
 * @property Datrrwt $idrwt0
 */
abstract class BaseTindakanIgd extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tindakan_igd';
	}

	public static function representingColumn() {
		return 'qty';
	}

	public function rules() {
		return array(
			array('idreg, kdtindakan, qty, harga_satuan, jns_bayar', 'required'),
			array('idreg, idrwt, kdtindakan, jns_bayar', 'numerical', 'integerOnly'=>true),
			array('qty, harga_satuan', 'length', 'max'=>10),
			array('idrwt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idreg, idrwt, kdtindakan, qty, harga_satuan, jns_bayar', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idreg0' => array(self::BELONGS_TO, 'RegisterIgd', 'idreg'),
			'kdtindakan0' => array(self::BELONGS_TO, 'Dattarif', 'kdtindakan'),
			'idrwt0' => array(self::BELONGS_TO, 'Datrrwt', 'idrwt'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idreg' => Yii::t('app', 'Idreg'),
			'idrwt' => Yii::t('app', 'Idrwt'),
			'kdtindakan' => Yii::t('app', 'Kdtindakan'),
			'qty' => Yii::t('app', 'Qty'),
			'harga_satuan' => Yii::t('app', 'Harga Satuan'),
			'jns_bayar' => Yii::t('app', 'Jns Bayar'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idreg', $this->idreg);
		$criteria->compare('idrwt', $this->idrwt);
		$criteria->compare('kdtindakan', $this->kdtindakan);
		$criteria->compare('qty', $this->qty, true);
		$criteria->compare('harga_satuan', $this->harga_satuan, true);
		$criteria->compare('jns_bayar', $this->jns_bayar);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}