<?php

/**
 * This is the model base class for the table "reftype".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Reftype".
 *
 * Columns in table "reftype" available as properties of the model,
 * followed by relations of table "reftype" available as properties of the model.
 *
 * @property integer $id
 * @property string $type
 *
 * @property Datregister[] $datregisters
 */
abstract class BaseReftype extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'reftype';
	}

	public static function representingColumn() {
		return 'type';
	}

	public function rules() {
		return array(
			array('type', 'required'),
			array('type', 'length', 'max'=>45),
			array('id, type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'datregisters' => array(self::HAS_MANY, 'Datregister', 'type'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'type' => Yii::t('app', 'Type'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('type', $this->type, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}