<?php

/**
 * This is the model base class for the table "refsex".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Refsex".
 *
 * Columns in table "refsex" available as properties of the model,
 * followed by relations of table "refsex" available as properties of the model.
 *
 * @property integer $id
 * @property string $sex
 *
 * @property Mspasien2[] $mspasien2s
 */
abstract class BaseRefsex extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'refsex';
	}

	public static function representingColumn() {
		return 'sex';
	}

	public function rules() {
		return array(
			array('sex', 'required'),
			array('sex', 'length', 'max'=>45),
			array('id, sex', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mspasien2s' => array(self::HAS_MANY, 'Mspasien2', 'sex'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'sex' => Yii::t('app', 'Sex'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('sex', $this->sex, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}