<?php

/**
 * This is the model base class for the table "ruang_rawat".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RuangRawat".
 *
 * Columns in table "ruang_rawat" available as properties of the model,
 * followed by relations of table "ruang_rawat" available as properties of the model.
 *
 * @property integer $id
 * @property string $ruangan
 * @property string $kdruang
 * @property integer $peruntukan
 * @property integer $kelas
 * @property string $tarif
 * @property string $foto
 *
 * @property Datrrwt[] $datrrwts
 * @property Kamar[] $kamars
 * @property Refperuntukan $peruntukan0
 * @property Refkelasrawat $kelas0
 */
abstract class BaseRuangRawat extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ruang_rawat';
	}

	public static function representingColumn() {
		return 'ruangan';
	}

	public function rules() {
		return array(
			array('ruangan, kdruang, peruntukan, kelas, tarif', 'required'),
			array('peruntukan, kelas', 'numerical', 'integerOnly'=>true),
			array('ruangan, kdruang, foto', 'length', 'max'=>45),
			array('tarif', 'length', 'max'=>10),
			array('foto', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ruangan, kdruang, peruntukan, kelas, tarif, foto', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'datrrwts' => array(self::HAS_MANY, 'Datrrwt', 'ruang'),
			'kamars' => array(self::HAS_MANY, 'Kamar', 'idruang'),
			'peruntukan0' => array(self::BELONGS_TO, 'Refperuntukan', 'peruntukan'),
			'kelas0' => array(self::BELONGS_TO, 'Refkelasrawat', 'kelas'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ruangan' => Yii::t('app', 'Ruangan'),
			'kdruang' => Yii::t('app', 'Kdruang'),
			'peruntukan' => Yii::t('app', 'Peruntukan'),
			'kelas' => Yii::t('app', 'Kelas'),
			'tarif' => Yii::t('app', 'Tarif'),
			'foto' => Yii::t('app', 'Foto'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ruangan', $this->ruangan, true);
		$criteria->compare('kdruang', $this->kdruang, true);
		$criteria->compare('peruntukan', $this->peruntukan);
		$criteria->compare('kelas', $this->kelas);
		$criteria->compare('tarif', $this->tarif, true);
		$criteria->compare('foto', $this->foto, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}