<?php

/**
 * This is the model base class for the table "dattarif".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Dattarif".
 *
 * Columns in table "dattarif" available as properties of the model,
 * followed by relations of table "dattarif" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idtindakan
 * @property string $tindakan
 * @property integer $kdtambah
 * @property integer $type
 * @property string $tarif
 *
 * @property Reftype $type0
 * @property Reftindakan $idtindakan0
 * @property RefKodeTambah $kdtambah0
 * @property Dattindakan[] $dattindakans
 * @property TindakanIgd[] $tindakanIgds
 */
abstract class BaseDattarif extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'dattarif';
	}

	public static function representingColumn() {
		return 'tindakan';
	}

	public function rules() {
		return array(
			array('idtindakan, tindakan, kdtambah, tarif', 'required'),
			array('idtindakan, kdtambah, type', 'numerical', 'integerOnly'=>true),
			array('tindakan', 'length', 'max'=>45),
			array('tarif', 'length', 'max'=>10),
			array('type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idtindakan, tindakan, kdtambah, type, tarif', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'type0' => array(self::BELONGS_TO, 'Reftype', 'type'),
			'idtindakan0' => array(self::BELONGS_TO, 'Reftindakan', 'idtindakan'),
			'kdtambah0' => array(self::BELONGS_TO, 'RefKodeTambah', 'kdtambah'),
			'dattindakans' => array(self::HAS_MANY, 'Dattindakan', 'kdtindakan'),
			'tindakanIgds' => array(self::HAS_MANY, 'TindakanIgd', 'kdtindakan'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idtindakan' => Yii::t('app', 'Idtindakan'),
			'tindakan' => Yii::t('app', 'Tindakan'),
			'kdtambah' => Yii::t('app', 'Kdtambah'),
			'type' => Yii::t('app', 'Type'),
			'tarif' => Yii::t('app', 'Tarif'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idtindakan', $this->idtindakan);
		$criteria->compare('tindakan', $this->tindakan, true);
		$criteria->compare('kdtambah', $this->kdtambah);
		$criteria->compare('type', $this->type);
		$criteria->compare('tarif', $this->tarif, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}