<?php

/**
 * This is the model base class for the table "kategori_tindakan".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "KategoriTindakan".
 *
 * Columns in table "kategori_tindakan" available as properties of the model,
 * followed by relations of table "kategori_tindakan" available as properties of the model.
 *
 * @property integer $id
 * @property integer $parent
 * @property string $kategori
 *
 * @property KategoriTindakan $parent0
 * @property KategoriTindakan[] $kategoriTindakans
 * @property Reftindakan[] $reftindakans
 */
abstract class BaseKategoriTindakan extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'kategori_tindakan';
	}

	public static function representingColumn() {
		return 'kategori';
	}

	public function rules() {
		return array(
			array('kategori', 'required'),
			array('parent', 'numerical', 'integerOnly'=>true),
			array('kategori', 'length', 'max'=>45),
			array('parent', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, parent, kategori', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'parent0' => array(self::BELONGS_TO, 'KategoriTindakan', 'parent'),
			'kategoriTindakans' => array(self::HAS_MANY, 'KategoriTindakan', 'parent'),
			'reftindakans' => array(self::HAS_MANY, 'Reftindakan', 'idkategori'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'parent' => Yii::t('app', 'Parent'),
			'kategori' => Yii::t('app', 'Kategori'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('parent', $this->parent);
		$criteria->compare('kategori', $this->kategori, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}