<?php

/**
 * This is the model base class for the table "labrec".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Labrec".
 *
 * Columns in table "labrec" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $kd_pasien
 * @property string $kd_lab
 * @property string $tgl_masuk
 * @property string $tgl_lab
 * @property string $jenis
 * @property string $register
 * @property string $kd_dokter
 * @property string $keterangan
 * @property string $nm_dokter
 *
 */
abstract class BaseLabrec extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'labrec';
	}

	public static function representingColumn() {
		return 'kd_pasien';
	}

	public function rules() {
		return array(
			array('kd_pasien, kd_lab, tgl_masuk, jenis, register', 'required'),
			array('kd_pasien, register', 'length', 'max'=>17),
			array('kd_lab, kd_dokter', 'length', 'max'=>12),
			array('jenis', 'length', 'max'=>1),
			array('keterangan', 'length', 'max'=>25),
			array('nm_dokter', 'length', 'max'=>40),
			array('tgl_lab', 'safe'),
			array('tgl_lab, kd_dokter, keterangan, nm_dokter', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, kd_pasien, kd_lab, tgl_masuk, tgl_lab, jenis, register, kd_dokter, keterangan, nm_dokter', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'kd_pasien' => Yii::t('app', 'Kd Pasien'),
			'kd_lab' => Yii::t('app', 'Kd Lab'),
			'tgl_masuk' => Yii::t('app', 'Tgl Masuk'),
			'tgl_lab' => Yii::t('app', 'Tgl Lab'),
			'jenis' => Yii::t('app', 'Jenis'),
			'register' => Yii::t('app', 'Register'),
			'kd_dokter' => Yii::t('app', 'Kd Dokter'),
			'keterangan' => Yii::t('app', 'Keterangan'),
			'nm_dokter' => Yii::t('app', 'Nm Dokter'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('kd_pasien', $this->kd_pasien, true);
		$criteria->compare('kd_lab', $this->kd_lab, true);
		$criteria->compare('tgl_masuk', $this->tgl_masuk, true);
		$criteria->compare('tgl_lab', $this->tgl_lab, true);
		$criteria->compare('jenis', $this->jenis, true);
		$criteria->compare('register', $this->register, true);
		$criteria->compare('kd_dokter', $this->kd_dokter, true);
		$criteria->compare('keterangan', $this->keterangan, true);
		$criteria->compare('nm_dokter', $this->nm_dokter, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}