<?php

/**
 * This is the model base class for the table "refruang".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Refruang".
 *
 * Columns in table "refruang" available as properties of the model,
 * followed by relations of table "refruang" available as properties of the model.
 *
 * @property integer $id
 * @property string $refruang
 *
 * @property Kamar[] $kamars
 */
abstract class BaseRefruang extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'refruang';
	}

	public static function representingColumn() {
		return 'refruang';
	}

	public function rules() {
		return array(
			array('refruang', 'required'),
			array('refruang', 'length', 'max'=>45),
			array('id, refruang', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'kamars' => array(self::HAS_MANY, 'Kamar', 'ruangan'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'refruang' => Yii::t('app', 'Refruang'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('refruang', $this->refruang, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}