<?php

/**
 * This is the model base class for the table "refpembayaran".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Refpembayaran".
 *
 * Columns in table "refpembayaran" available as properties of the model,
 * followed by relations of table "refpembayaran" available as properties of the model.
 *
 * @property integer $id
 * @property string $via
 *
 * @property Deposit[] $deposits
 */
abstract class BaseRefpembayaran extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'refpembayaran';
	}

	public static function representingColumn() {
		return 'via';
	}

	public function rules() {
		return array(
			array('via', 'required'),
			array('via', 'length', 'max'=>45),
			array('id, via', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'deposits' => array(self::HAS_MANY, 'Deposit', 'via'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'via' => Yii::t('app', 'Via'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('via', $this->via, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}