<?php

/**
 * This is the model base class for the table "suratkelahiran".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Suratkelahiran".
 *
 * Columns in table "suratkelahiran" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $tgl
 * @property string $nosurat
 * @property string $nama
 * @property string $ibu
 * @property string $ayah
 * @property string $alamat1
 * @property string $alamat2
 * @property string $tgllahir
 * @property string $jam
 * @property string $berat
 * @property string $panjang
 * @property string $hidupmati
 * @property integer $dokter
 * @property integer $bidan
 *
 */
abstract class BaseSuratkelahiran extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'suratkelahiran';
	}

	public static function representingColumn() {
		return 'tgl';
	}

	public function rules() {
		return array(
			array('tgl, nosurat, ibu, alamat1, tgllahir, jam, berat, panjang, hidupmati', 'required'),
			array('dokter, bidan', 'numerical', 'integerOnly'=>true),
			array('nosurat, nama, ibu, ayah, alamat1, alamat2', 'length', 'max'=>45),
			array('berat, panjang', 'length', 'max'=>10),
			array('hidupmati', 'length', 'max'=>1),
			array('nama, ayah, alamat2, dokter, bidan', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, tgl, nosurat, nama, ibu, ayah, alamat1, alamat2, tgllahir, jam, berat, panjang, hidupmati, dokter, bidan', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'tgl' => Yii::t('app', 'Tgl'),
			'nosurat' => Yii::t('app', 'Nosurat'),
			'nama' => Yii::t('app', 'Nama'),
			'ibu' => Yii::t('app', 'Ibu'),
			'ayah' => Yii::t('app', 'Ayah'),
			'alamat1' => Yii::t('app', 'Alamat1'),
			'alamat2' => Yii::t('app', 'Alamat2'),
			'tgllahir' => Yii::t('app', 'Tgllahir'),
			'jam' => Yii::t('app', 'Jam'),
			'berat' => Yii::t('app', 'Berat'),
			'panjang' => Yii::t('app', 'Panjang'),
			'hidupmati' => Yii::t('app', 'Hidupmati'),
			'dokter' => Yii::t('app', 'Dokter'),
			'bidan' => Yii::t('app', 'Bidan'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('tgl', $this->tgl, true);
		$criteria->compare('nosurat', $this->nosurat, true);
		$criteria->compare('nama', $this->nama, true);
		$criteria->compare('ibu', $this->ibu, true);
		$criteria->compare('ayah', $this->ayah, true);
		$criteria->compare('alamat1', $this->alamat1, true);
		$criteria->compare('alamat2', $this->alamat2, true);
		$criteria->compare('tgllahir', $this->tgllahir, true);
		$criteria->compare('jam', $this->jam, true);
		$criteria->compare('berat', $this->berat, true);
		$criteria->compare('panjang', $this->panjang, true);
		$criteria->compare('hidupmati', $this->hidupmati, true);
		$criteria->compare('dokter', $this->dokter);
		$criteria->compare('bidan', $this->bidan);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}