<?php

/**
 * This is the model base class for the table "datsjp".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Datsjp".
 *
 * Columns in table "datsjp" available as properties of the model,
 * followed by relations of table "datsjp" available as properties of the model.
 *
 * @property integer $id
 * @property string $nosjp
 * @property string $tglsjp
 * @property integer $nokapst
 *
 * @property Mspasien2 $nokapst0
 */
abstract class BaseDatsjp extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'datsjp';
	}

	public static function representingColumn() {
		return 'nosjp';
	}

	public function rules() {
		return array(
			array('nosjp, tglsjp, nokapst', 'required'),
			array('nokapst', 'numerical', 'integerOnly'=>true),
			array('nosjp', 'length', 'max'=>45),
			array('id, nosjp, tglsjp, nokapst', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'nokapst0' => array(self::BELONGS_TO, 'Mspasien2', 'nokapst'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nosjp' => Yii::t('app', 'No sjp'),
			'tglsjp' => Yii::t('app', 'Tanggal '),
			'nokapst' => Yii::t('app', 'Member'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nosjp', $this->nosjp, true);
		$criteria->compare('tglsjp', $this->tglsjp, true);
		$criteria->compare('nokapst', $this->nokapst);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}