<?php

/**
 * This is the model base class for the table "refdati".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Refdati".
 *
 * Columns in table "refdati" available as properties of the model,
 * followed by relations of table "refdati" available as properties of the model.
 *
 * @property integer $id
 * @property string $KDPROP
 * @property string $KDDATI2
 * @property string $NMDATI2
 *
 * @property Mspasien2[] $mspasien2s
 */
abstract class BaseRefdati extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'refdati';
	}

	public static function representingColumn() {
		return 'KDPROP';
	}

	public function rules() {
		return array(
			array('KDPROP, KDDATI2, NMDATI2', 'required'),
			array('KDPROP', 'length', 'max'=>2),
			array('KDDATI2', 'length', 'max'=>4),
			array('NMDATI2', 'length', 'max'=>25),
			array('id, KDPROP, KDDATI2, NMDATI2', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mspasien2s' => array(self::HAS_MANY, 'Mspasien2', 'dati'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'KDPROP' => Yii::t('app', 'Kdprop'),
			'KDDATI2' => Yii::t('app', 'Kddati2'),
			'NMDATI2' => Yii::t('app', 'Nmdati2'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('KDPROP', $this->KDPROP, true);
		$criteria->compare('KDDATI2', $this->KDDATI2, true);
		$criteria->compare('NMDATI2', $this->NMDATI2, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}