<?php

/**
 * This is the model base class for the table "dattindakan".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Dattindakan".
 *
 * Columns in table "dattindakan" available as properties of the model,
 * followed by relations of table "dattindakan" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idreg
 * @property integer $kdtindakan
 * @property integer $qty
 * @property string $harga_satuan
 *
 * @property Dattarif $kdtindakan0
 * @property Datregister $idreg0
 */
abstract class BaseDattindakan extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'dattindakan';
	}

	public static function representingColumn() {
		return 'harga_satuan';
	}

	public function rules() {
		return array(
			array('idreg, kdtindakan, qty, harga_satuan', 'required'),
			array('idreg, kdtindakan, qty', 'numerical', 'integerOnly'=>true),
			array('harga_satuan', 'length', 'max'=>10),
			array('id, idreg, kdtindakan, qty, harga_satuan', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'kdtindakan0' => array(self::BELONGS_TO, 'Dattarif', 'kdtindakan'),
			'idreg0' => array(self::BELONGS_TO, 'Datregister', 'idreg'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idreg' => Yii::t('app', 'Idreg'),
			'kdtindakan' => Yii::t('app', 'Kdtindakan'),
			'qty' => Yii::t('app', 'Qty'),
			'harga_satuan' => Yii::t('app', 'Harga Satuan'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idreg', $this->idreg);
		$criteria->compare('kdtindakan', $this->kdtindakan);
		$criteria->compare('qty', $this->qty);
		$criteria->compare('harga_satuan', $this->harga_satuan, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}