<?php

/**
 * This is the model base class for the table "labrecdetil".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Labrecdetil".
 *
 * Columns in table "labrecdetil" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $kd_pasien
 * @property string $kd_lab
 * @property string $tgl_masuk
 * @property string $tgl_lab
 * @property string $hasil
 * @property string $kd_labh
 * @property string $kd_labd
 *
 */
abstract class BaseLabrecdetil extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'labrecdetil';
	}

	public static function representingColumn() {
		return 'kd_pasien';
	}

	public function rules() {
		return array(
			array('kd_pasien, kd_lab, tgl_masuk, kd_labh, kd_labd', 'required'),
			array('kd_pasien', 'length', 'max'=>17),
			array('kd_lab', 'length', 'max'=>12),
			array('hasil', 'length', 'max'=>100),
			array('kd_labh, kd_labd', 'length', 'max'=>3),
			array('tgl_lab', 'safe'),
			array('tgl_lab, hasil', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, kd_pasien, kd_lab, tgl_masuk, tgl_lab, hasil, kd_labh, kd_labd', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'kd_pasien' => Yii::t('app', 'Kd Pasien'),
			'kd_lab' => Yii::t('app', 'Kd Lab'),
			'tgl_masuk' => Yii::t('app', 'Tgl Masuk'),
			'tgl_lab' => Yii::t('app', 'Tgl Lab'),
			'hasil' => Yii::t('app', 'Hasil'),
			'kd_labh' => Yii::t('app', 'Kd Labh'),
			'kd_labd' => Yii::t('app', 'Kd Labd'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('kd_pasien', $this->kd_pasien, true);
		$criteria->compare('kd_lab', $this->kd_lab, true);
		$criteria->compare('tgl_masuk', $this->tgl_masuk, true);
		$criteria->compare('tgl_lab', $this->tgl_lab, true);
		$criteria->compare('hasil', $this->hasil, true);
		$criteria->compare('kd_labh', $this->kd_labh, true);
		$criteria->compare('kd_labd', $this->kd_labd, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}