<?php

/**
 * This is the model base class for the table "refstatusnikah".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Refstatusnikah".
 *
 * Columns in table "refstatusnikah" available as properties of the model,
 * followed by relations of table "refstatusnikah" available as properties of the model.
 *
 * @property integer $id
 * @property string $status
 *
 * @property Mspasien2[] $mspasien2s
 */
abstract class BaseRefstatusnikah extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'refstatusnikah';
	}

	public static function representingColumn() {
		return 'status';
	}

	public function rules() {
		return array(
			array('status', 'required'),
			array('status', 'length', 'max'=>45),
			array('id, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mspasien2s' => array(self::HAS_MANY, 'Mspasien2', 'status'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}