<?php

/**
 * This is the model base class for the table "obat".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Obat".
 *
 * Columns in table "obat" available as properties of the model,
 * followed by relations of table "obat" available as properties of the model.
 *
 * @property integer $id
 * @property string $nomor
 * @property string $sub
 * @property integer $idobat
 * @property string $kode
 * @property string $obatcol
 *
 * @property Refobat $idobat0
 */
abstract class BaseObat extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'obat';
	}

	public static function representingColumn() {
		return 'nomor';
	}

	public function rules() {
		return array(
			array('id, nomor, sub, kode, obatcol', 'required'),
			array('id, idobat', 'numerical', 'integerOnly'=>true),
			array('nomor, sub, kode, obatcol', 'length', 'max'=>45),
			array('idobat', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nomor, sub, idobat, kode, obatcol', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idobat0' => array(self::BELONGS_TO, 'Refobat', 'idobat'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nomor' => Yii::t('app', 'Nomor'),
			'sub' => Yii::t('app', 'Sub'),
			'idobat' => Yii::t('app', 'Idobat'),
			'kode' => Yii::t('app', 'Kode'),
			'obatcol' => Yii::t('app', 'Obatcol'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nomor', $this->nomor, true);
		$criteria->compare('sub', $this->sub, true);
		$criteria->compare('idobat', $this->idobat);
		$criteria->compare('kode', $this->kode, true);
		$criteria->compare('obatcol', $this->obatcol, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}