<?php

/**
 * This is the model base class for the table "bed".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Bed".
 *
 * Columns in table "bed" available as properties of the model,
 * followed by relations of table "bed" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idkamar
 * @property integer $nomor
 * @property integer $terisi
 *
 * @property Kamar $idkamar0
 */
abstract class BaseBed extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'bed';
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('idkamar, nomor, terisi', 'required'),
			array('idkamar, nomor, terisi', 'numerical', 'integerOnly'=>true),
			array('id, idkamar, nomor, terisi', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idkamar0' => array(self::BELONGS_TO, 'Kamar', 'idkamar'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idkamar' => Yii::t('app', 'Idkamar'),
			'nomor' => Yii::t('app', 'Nomor'),
			'terisi' => Yii::t('app', 'Terisi'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idkamar', $this->idkamar);
		$criteria->compare('nomor', $this->nomor);
		$criteria->compare('terisi', $this->terisi);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}