<?php

/**
 * This is the model base class for the table "kamar".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Kamar".
 *
 * Columns in table "kamar" available as properties of the model,
 * followed by relations of table "kamar" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idruang
 * @property integer $nomor
 *
 * @property Bed[] $beds
 * @property Datrrwt[] $datrrwts
 * @property RuangRawat $idruang0
 */
abstract class BaseKamar extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'kamar';
	}

	public static function representingColumn() {
		return 'nomor';
	}

	public function rules() {
		return array(
			array('idruang, nomor', 'required'),
			array('idruang, nomor', 'numerical', 'integerOnly'=>true),
			array('id, idruang, nomor', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'beds' => array(self::HAS_MANY, 'Bed', 'idkamar'),
			'datrrwts' => array(self::HAS_MANY, 'Datrrwt', 'kamar'),
			'idruang0' => array(self::BELONGS_TO, 'RuangRawat', 'idruang'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idruang' => Yii::t('app', 'Idruang'),
			'nomor' => Yii::t('app', 'Nomor'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idruang', $this->idruang);
		$criteria->compare('nomor', $this->nomor);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}