<?php

/**
 * This is the model base class for the table "labh".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Labh".
 *
 * Columns in table "labh" available as properties of the model,
 * followed by relations of table "labh" available as properties of the model.
 *
 * @property integer $id
 * @property string $kd_labh2
 * @property string $ur_labh
 *
 * @property Labd[] $labds
 */
abstract class BaseLabh extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'labh';
	}

	public static function representingColumn() {
		return 'kd_labh2';
	}

	public function rules() {
		return array(
			array('kd_labh2', 'required'),
			array('kd_labh2', 'length', 'max'=>3),
			array('ur_labh', 'length', 'max'=>30),
			array('ur_labh', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, kd_labh2, ur_labh', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'labds' => array(self::HAS_MANY, 'Labd', 'idlabh'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'kd_labh2' => Yii::t('app', 'Kd Labh2'),
			'ur_labh' => Yii::t('app', 'Ur Labh'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('kd_labh2', $this->kd_labh2, true);
		$criteria->compare('ur_labh', $this->ur_labh, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}